baseurl: '/empty-jekyll-site'
permalink: /:year/:month/:title.html

title:
  'my empty site'
description:
  'aenean congue dui a lectus aliquam, quis imperdiet purus dignissim.'
author:
  name: 'John Appleseed'
  url: 'mailto:john@example.com'

defaults:
  -
    scope:
      path: ''
    values:
      layout: base
  -
    scope:
      path: ''
      type: posts
    values:
      layout: post
